# Generated by Django 5.0 on 2023-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCode', models.CharField(max_length=6)),
                ('ItemName', models.CharField(max_length=30)),
                ('ItemDesc', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=10)),
                ('Manufacturer', models.CharField(max_length=30)),
            ],
        ),
    ]
